package com.kreativesquadz.billkit.ui.customerManag

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.activityViewModels
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import com.kreativesquadz.billkit.BR
import com.kreativesquadz.billkit.R
import com.kreativesquadz.billkit.adapter.GenericAdapter
import com.kreativesquadz.billkit.databinding.FragmentCustomerManagementBinding
import com.kreativesquadz.billkit.interfaces.OnItemClickListener
import com.kreativesquadz.billkit.model.Customer

class CustomerManagementFrag : Fragment() {
    var _binding: FragmentCustomerManagementBinding? = null
    val binding get() = _binding!!
    private lateinit var adapter: GenericAdapter<Customer>
    private val viewModel: CustomerManagementViewModel by activityViewModels()


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel.getCustomers()
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentCustomerManagementBinding.inflate(inflater, container, false)
        setupRecyclerView()
        observers()
        onClickListeners()

        return binding.root
    }

    fun onClickListeners(){
        binding.btnCreateCustomer.setOnClickListener {
            findNavController().navigate(R.id.action_customerManagementFrag_to_createCustomerFrag)
        }
    }

    fun observers(){
        viewModel.customer.observe(viewLifecycleOwner) {
            if (it.data != null){
                adapter.submitList(it.data)
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }


    private fun setupRecyclerView() {
        adapter = GenericAdapter(
            viewModel.customer.value?.data ?: emptyList(),
            object : OnItemClickListener<Customer> {
                override fun onItemClick(item: Customer) {
                    // Handle item click
                }
            },
            R.layout.item_customer,
            BR.customer // Variable ID generated by data binding
        )
        binding.recyclerView.adapter = adapter
        binding.recyclerView.layoutManager = LinearLayoutManager(context)
    }



}